apiVersion: v1
kind: Service
metadata:
  name: rfr-url-shortener-redis
  labels:
    app.kubernetes.io/name: url-shortener-redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: redis-failover
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app.kubernetes.io/name: url-shortener-redis
    app.kubernetes.io/component: redis
