apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: analytics-service
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: url-shortener
spec:
  parentRefs:
    - name: shortener-gateway
      namespace: url-shortener
  hostnames:
    - "analytics.example.k8s.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: analytics-service
          port: 80
