apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortener-service
  labels:
    app.kubernetes.io/name: shortener-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: url-shortener
  annotations:
    # nginx-ingress
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    # traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: nginx
  rules:
    - host: url-shortener.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shortener-service
                port:
                  name: http
  tls:
    - hosts:
        - url-shortener.example.com
      secretName: shortener-tls
