apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shortener-service
  labels:
    app.kubernetes.io/name: shortener-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: url-shortener
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shortener-service
