apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortener-service
spec:
  ingressClassName: nginx
  rules:
    - host: url-shortener.dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-shortener-service
                port:
                  name: http
  tls:
    - hosts:
        - url-shortener.dev.example.com
      secretName: shortener-tls
