apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shortener-service
spec:
  parentRefs:
    - name: shortener-gateway
      namespace: url-shortener-staging
  hostnames:
    - "url-shortener.staging.k8s.local"
