apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shortener-service
spec:
  parentRefs:
    - name: shortener-gateway
      namespace: url-shortener-staging
  hostnames:
    - "url-shortener.staging.k8s.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: staging-shortener-service
          port: 80
