apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: url-shortener-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  # Application Deployments
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment

  # Middleware - staging configuration
  - path: postgres-patch.yaml
  - path: redis-patch.yaml
  - path: rabbitmq-patch.yaml

  # Ingress - staging hostname
  - path: ingress-patch.yaml
