---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: url-shortener-staging
spec:
  encryptedData:
    password: AgA4OfBwotbsRh6IpXpawHgGlQcjfxpsmn0CgjvmhWRnac7qX62j/wXHiqtieiR1nSPLpyl/dtdaBsfDM29+LwptivEOA0Zd/ibCeHNMrxGVYTqvS2K1KPX142pF1ZqV8kiYaONCOZ6l6GhxS2Hz1MguCDHo0QgSxtLsgql+LNeA0ERjBPRX1lwBfdhx0xnrigRISCt8vw1iGa5D0CeJyq9+gRH2ejm+jmyuTsGTE8VrnVjiFlm2OjRI+KuAdzuYAeFS9X0a97DZ7UZhEyTpOka/i4cElRW9q6eJLBKCqORJLuAr2lsPmrtSfTK6zL6u93CgHGVOguONFdP/bgp96f7emE4PJTnmlNFAeH3wpnggid4JqHZi9yF1OLn6PLs+nLB9Wqamha8ZQdgqxID3EAhv/4w4D15+AG0gXvOgE0yksl6ooLhYpHjPs4RBDlu4iVIfjT4LO8QDiUoG7RkRvejA4DIYpKfxVSvgbXPhLsIOFKLu7tV7udtT5IByNEB3btVp6DqkLPDteMSAB+Q4iDLrnUDtJGXAnVIdzugXbS/2WXRlt0EPEdEqugiW7of6LASTOeswz7Dd97SNQKYOgFaOKT/pzytULcX0pgN7rQJ3dis+3cUnXdyCAcKYBQ92Inl9EHt7KB3n0+f1IAgbXziFrFiciEBybTYsicAWhLWmJ+gwDmkD9evv4YVDX2JzAfctq2v2LNVOogeqWDo=
    username: AgAkwyZajoQuWsu/zlLqeQc0v/WqiBkCS02M+83yqNlMPNr+Nj4vi6T7oCphYFCEKXC75KmQKSniq0XTfuZVvRYA1W4n96cSPLgeHR4Rsekku3d39kq45QMIJGzQ6iBVdKSkyQ6EMXaBQT4qd2vqCDscomJoVfTtYaCy4pFiA9liRCTYwcQgvnUGF6HyLtZpGR8zSiA1AA4sxejf01yMhSPCtIITpx4kpovbVVtYmM2szyo1m9mEWJzyUCFNsY28cbjF/4aztepUuFPUW8UFVil+phR5SrRXCJqS2CAxNyLsG2LdN7qVeTu70NnEEaeocFs/ozDiEk6vXA8lm48IJ0LUZ2PDUvx+CvJwznUkdmskRfy0MBIFGRmKT+PcW+SxN7zpkxMFQg9gqSWO7KwaQ8cB1EnAKxHtc03QDITweLlewpgKGWtXD1jOjoRo7D3nhT2BWK7b2ifrnmllgn5GnptpM3wrpFWtoWxn2HMk2ms1QI3kKh9ftE6dEPnmkH10grXdvhtiN/oSzQmb0pnuIexgN4E5OEGvsoatn1NaiGcAVrTAQjGoNtYb0j3BrWE85BF5YUjT5vDGBRwgIdw2X2Rirf2S7W3ubLJXWEymQZaKcPsAYtQzLMB1dZIiCH3lO3wxkx9FdSqQLgzfD/JuDRF/nYueEet5BOoQY8vRWiKSJkQT4Zgmoe5XRMXFygJY3fxaI7HeDERHhOvfkTQ=
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: url-shortener-staging
