---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: rabbitmq-credentials
  namespace: url-shortener-staging
spec:
  encryptedData:
    password: AgCp6aVlrO5Zh39gk8XL4iluzS175ULZxNcSPZ6HJoRsohv8dpV2v4Crq9zRmUrPoUSzkXRZ3RhyqgskueTihYvAR9wYcGKak36/jal3QYgP0WIbMshHstv1nFiXqS1Jfo5qQiHQNPdze4J7s2974JOwuyIIzMNGZqt1o9qe8kLo+SYeeL6PjF+wjgTtLR0BmcyhiqCgjpnF01x90dKaf7qZx6mPrC9qNpCFjcpsEKNhAdu9qpuaTX5LmRsyo2CXcPjG3rCfj6pi3KMOZMJC9b+xT+Nb02i+G62sYdVJVUfwFkfNNI9PgdNKyonvnQhaGmkr7p93oBoFu69+dRcwmSO5r3XIrK4oS8068+E8pwLRek+NSmS/gSiQlHooR1cKDx7D3nTjijrM0LH1e9bML4sU96vSv71mBPSkMKtF15QPFwjkDHI5s0nTWYnpScukNh0ktcxKGhBQxKA8NNVf5yUAbvwDHfFwzbx7uJLW68kPIeiXPz9Owolkz43AOUFGhKeAMgwUCxttuWO3OYn1qMcQL99E41RkFttBfOT3AIyeuxP/6dOeo8PA9vWgfK36WP4muHI3Y9byKQFTTmu9zi+qtX0840CS4RvYIKVpbW+qCnLZgkhoR84DzAXLPFKrx3KonNFC3Lh1mISb10OZ97ymcvzXWIZIV+ITDagOCtTsaa8M9J3R/sKJOchQsZHY+4yzoUrhfZJIVAdt+KQ=
    username: AgCU8QixVx7KpGb9mLa4BGqcWEnglZLv5//Yda3W8ZPfH8U3TlQYgg2of9d8Solv33h35MuEPzDElRk9qjW2eTWnrbD5qRWwYcpqbS9TIRrFX69JZD8xfWkSGFoazB21PrqgO2haMNmLVpyeE/IZn6YRWYv+a4KNljrzVBBvjTrXiZ7LH8YiB3pN0d2PihIjf1H+fPwtGBSarof0iho8BMTFomafnhYr5hGi7OEzw05jBhu1ULebeHFrSMoBr9qSnQUMT6TYhOnC9P3Ei7X2jNI+uqJsXgDnBB4FCdifh8O7zoFkgUoLknaf5iAFoMkAxJBQUvk5X8dji30HT5Em4ZHrXWPoQ/3OehIfJQSJzdc7ZBJyc6173xJ0L9nzZs+CyId4O1hGSewys7YBAhE46ASgYYDvFUR1D0nJLE8AW9bcyH+l3+BO/zwLG940d2x1mz03lt4bE/PM5+6brbPBq9l2HKds9PTPMaVpjYw+uFpMTwfWXV6wBHdFC5W/9Wu1fnwx94KkW4QX92horykamxwyns1FVp+EGaBZx/pARvcJp37dGiLa/cX0E9R76Vkd96onrhMkxohgREBFrFhALFY4d1nDaANdrps93TZ40M7vvEmWMAy/zElj1aJjze3zPclnamuKFDx8+wtmRGjDgR8N1mor/B9HJ9Mge0SS6Dkh+JOprdFnjYu2QHQv/X9ZyfX1Q1ASOTK++2fVAFk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: rabbitmq-credentials
      namespace: url-shortener-staging
