---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: url-shortener-staging
spec:
  encryptedData:
    password: AgBgySDOZiUqsgFJgLTztOzn4HWYwZykPELw1U3rOrPhg/F1qbEsOGvhW2n49M/J8LYYls+6KlLZoc6kOuy98AJ12PtCvf5YhsJGX4kZz1f3KaABegKw3RPmqqj/x9QYSRxaO/7Vb+mHdr3OGnKQ4GhqbSjte/VIHCQoPH6YPvA9/tOW9SidGFRzf+2aSY5j1foTX5+Oy6niA+wKLYAYu2OjEJY+UskO0vqhKwcq+CT0awdh1ove9RszeaOcbWWp8r2XkToBu0k2rgDasjL9q4wQdJol+DCH3KTqHJhJ7ibUwgVp8qBc3KUmRqTskOQyfaTkzKzP08qpsbCaqvHDYxR4zKEmwNEg2RaqIP1RNY9G21dOKO30tBvcN6l/4g3ek9Z/9fijXN88/iNZkFdApHeviRTUMCmxKwfh8IDK7zwtbWOakauTKZodECIg3/kUZLUeanF1TIRYnBI5rgW1K3evgwUPLqtxxrERux2pT5bu8zhc2YS4JRQICQp1oCZd5aywLJ/1/X8PKdWoZkh4Yp6ZCYmhi7Z7SM0evq6JpQSt/Mj9CLFxFCmpVd7GCwjFhRjJbM1H+vUpF7jJY7M6zT3+SbGPcCXVydOVLToVXeFL1PFT26Tzt1d4PanYuCVWpBZmaEcuv6nYJH5xLGc4CzWu+nZzQjyK5eSdocAOIEex8fBUtTGHtZY3uhBGJAyIVjKLFygDbQGH+ZODHJRzEMiB6bYNQGQ=
    username: AgBRPKIz/AP1rNTOh+cmYuV8Zp5tolNCEOMaVaavVSuZb/8onpC+Vtpt4fJTV8ILCIOn0ezeV7n2uhJnM6dCO5wRKViSAuEs+bzRpp0p7ATi/ODTxmLD/L+t3PBldUwqOHt+sAWl4+VUY9NmIKkloae1YrTW/laaeujdKnKGSgJKEBt1kQS9N3v7eIVcq+T+i/7cWO3IOUYUMqgy2bNNQo34HpI3jTPROEf0RhKHO2XEv/kqyRZVyvyqySPluRix2ZIgKYBrZlxXwHjWTSgiOKXftgLWRFJh+A+HPgcnKelffWXLGKEI5RYG6/IcZNlsNNasfMSf8aXMyLbwWASmZPrBjpb5MKsFcJfHYGdDsQvZbwdsxvG7ikmkXMt8HADarex++fvoifwpXCFdNE9iB1WxiugoT0EZPToJjXheocmpPar1i9UjHuSeR93M5DTHXGSSh/vkhSei6I1IhEW00xwqecOegdF8MlvwpYFrj3XTaX991xmwgHeasujJXVKQ4KFXUDsOP2ihgIHe1D94Mh+ryvWJ5fQhOHCtbUBjYJXscVdBVsP4Vtx0d0y6SFmlenahNLKDejUJzaSAQOKSzcCqjIe78jCHDwQrTWmS0yQgJqwWoBfqDpYOjpo/E/AjZchZ6YBwFBUb92HUctl98ktWAzcXlSLsszbspicz7CyRnWdSKFxLiWgGLrUNBtt35DQfmubHBv5sM4Web7E=
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: url-shortener-staging
