---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-credentials
  namespace: url-shortener-staging
spec:
  encryptedData:
    password: AgCCkoCJju+dkiZbcwN/Ht4q56/fTPEu7w655a50iOtFcy7a/jTrEGzpQXaYIsJt6Z1DfcpC0WE9sGuP2DZfWhINVd1bjELPDy3E3MGq9w1HBOb7HpQUoXqVwYsYjmFEMrtoszxDDuglnnkTt1HhxIksOUt+lzFn01lzRXxaq/j/swKaumvKhvLks6Od7Sdu/x9vhKQRQbZwhkI/3bD8UiLewD41jqdVEcdA431hlRHcjnU+r7SD7yzxrUu0A8410zUkTp49IZmU7tSbkDczwt8WOEigBrBcOdzadV51Q2UcXxZWtY+H+8yHMlMmWy9yh7yTZF9DpJwjPrSfDL/ocNJ1e2L/Gwu3mo0EfV0bA3TIPtS+rzTruRbGM2IW2Wab5gVCIlLPbSPUAvfEjd3m33Uh9BvrS23BMFjtt4udFGmFI7SpTIfwVbWQxH5h+YWrzhUdZkIUSRvXDKPtxSPlQa+OymHY952FmNT/N0Sd9QyMXRLcopADTMf7SVAHexyhX1okDshqY7E59HaRUn+Yc71TrhZtgwLbfas+kXZWNC4+vO8W9KUP0EkXKLAWzcAcIFSmituTbZMdVIN8bL3OSRShB6ImZkN+rV4GZjbzs7nRtvVlLX2e24oZBTGckVKsszLEdlF4SQA0pLVuWbvYDP2echT+xRhGLLvVABuepmO4RoQ3jVjfID9h6KySEBdHkk01Z7ukDZL2lfHVNc8=
    username: AgAbNqHNemRERkKHBKQXhjhT+LoEJ5cCA/qbQ3ltXZSfhg3leFPqfSgGXABD9dDOGo+Hwu0BiadI6eerviu/Nlz1/H17przBg10gsAfgSamP4fEwxWm7GqyVcJgowety9E/fs8RZuCmoqoz2I1BDYt+BKaYKC3mKoIVJ+nVyUKdPS7yTckg25sm+HG+rv4zZsSxj7lKrJQZtI+wOOo7ttufzZeMa0aQIgQj/L/yLQKwfXl6MKNArW1kh50TwQMLg1/1icytKqBF1fFP0Xbh7e7S5eLovuzSnfgt9B2ktetD6667l7Jo1uvLTo89EliwVYW94MH1SB81gkhT219GoOB7v8TyjN/vit1QVwK7lc4C1VPGguirM37jeEshI/sL3yMdSOtSKL/xWGGrIay+09e5pNXKI+uBSJdi0fP5nwemQv0EaHM6iBHUFiEOYXMnLceT+MFwHxze+Ak2s3gAR1NdQiMQ3n3ZDFux4Ahn8uluAJBOZnh383KqzwNwfijdPwwUF8KHYd+D2CM/3xkb615CK+/LwJ8ZN3Hueg74s+MhzWg0TI1LYtLuL9Liie00RoqTylQdE7XhTzXV56qIumbtfIXqF9d8X/h+m0dnr8E2UBMbv6HdAcJ8FVFMIPKaez8BfU9hPZzmcq7NkbLlEmSRzrYHceuqyiPtWLvfgeombO5WlIrzemMEQ5EpZltNEp87gXpBYRCRIxLjzCe8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-credentials
      namespace: url-shortener-staging
