---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: url-shortener-staging
spec:
  encryptedData:
    password: AgB1kX2lcXyVXSKVnWqAOldSbRHuMasfiqSWTvaX1nvjhKUqdXo75sH4vMONbtC+PRPTOiFXtNfo7H37T9o00yKxv9Akyqpu9yXoqD5bvWnYxYJv6RNwjSmD8UiCMXCUubIwbBBNskUo5eVG3Hxry2X9SzJJRbwbF1pGZrgZTvXOEst0ol3s/MLiMy82e9Nt9L6p5BCgiqo3Cl1aJMjBs4TNm96rgSE9sKq8+m0tb9n0xE+rrugSrahSkdp4aBctWQn7mK0IBBJEgx6F+2TQbAyKZ7onOh2CBHwCcCXi1+85bgD4auVkaxaIJQVh53Z+N8We4oQEmYn+hCjO6fiJxPZvmkTXdCuvsAnBed0RF+QB6eGCwcujpLPClzqlcZDBg45WI+Vo29wy8+hOLXYT5gU5lYhVGizSWBN2LjRHI0EHULbjuhSauGpxcdSh/GRZ5vV9ZHSAVYUJ9viuTxAKeHPX3dqdMsMjEV4QOJt9rY1wjoS+0hOrwhKk4GInI7jGYtFPeclCgahA7Qogj63bkCJeqj9481iEOLcSbokKL0C1iuNiqQSRDp6MpEyT1V7V919renGohHi9ZM4hYYcE+kSfY96lhoc3H9ZAlSEUEzDkMAMFLxtwoSYE0b0T1Tsw9t2IkXMrN0yaB+TGMV89nR5fqxUGqtSWCS14hr7YIXhSYSw5jZztYTMJZl0uOjtV8OWhuExf8+aQD2j1Mqg=
    username: AgCOrMGGOGfF6tn9eHtSWLAKDadIxwe59b8jjBfYq39IAJX6C2O6Zr0nZVDK/p4JAPu8fR9IvyGrIjoK4mRreFEhwrs26PiPzJQh8/1SNu/2RusM36yhR1rntL1cV2uA0Bqpq41HeVTmbXOweLnF2W/uMcxMvsBY2WOiaLfZs7hSeR9EfoEAneZOu4Vv/gAQzDncRdDWrzebbwbxGMWA/lgCoG9DVv+OCOFMsKS5tbaVkpSHJwxkpRsOChYQD3WaB25B8h2UgBEmjoYE6ofP3n3Ftb0YlfzqKClxEZLO4xSKxjh3fZlG2OqAi4oTxnUKVzfvtbrwPi5tmWD4m/+WS5jSoJ4PiLP13jQyldjj5E0jnlf4xneydqXY1f/6tkm3pv9QMS7sevHJbQt8L4Ed/nzoXbzu9qIRaXVv/NAQctLA6yiq9S/lunkTTZTvVPa1SWSlgTtSH3ja8sz6RNml0395W93plZTJHUf91yv8daEXRbwE2OpP+6byN88fbktLDUs/fm9kX+LaW0kY/kCane6ilBk7HS7vzyIhQDBgDaTJGrObQKWXiGJvzORrGDH2rbnzPgGylq5tiVCQw2D/3KgIahC8j1PlGQfxvxJ4DG0jFFDBBnr6jk3JPFszWWyfHSUNgepzd+scMRK5qBp/QNDnVcMr+YnvaFlnQTP2NDck5uSbAPcW4yyf2IeI+YfGLlJd6p0APIeqhuqFtjk=
  template:
    metadata:
      name: postgres-credentials
      namespace: url-shortener-staging
