---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: url-shortener-staging
spec:
  encryptedData:
    password: AgA5bSx5BPHeStCxk6ZKUeFnvAeosuoJa3V5IIJIZFpDtky7oIUaSdI/nvHgQhVxGv4sJfwCIf7vOwjeqXCCgmUuLzVLNdieZRkGeAmxKOuOTNGwb0oyi0KivyK8XxiPuHLAkSWD9qEMQ851YmCWAcq1K+m3lJYNof5QddL9BzRIOZoMWU2Y+GEfJu6pxg8y3NhwCfZkkZIVwAUTYnSm3MEnYYJ5gwZwcFm4E+peey7Fozc4aWWplHcnvnGI5GqqoxT0syVS/zQjdTHpQ1uOx/nPGWSfisYbne82OBwZIQ6CgiSX1zuVyRDJh4lwYMrQ5otGabV18JwWtvZg1NDC4apAGQkbIgeZEwAdMZKM0CohHbNbf7ULiEeOdOLCtIJx+yLQJDlcDmzwMN9rOEHtxqT1XAk83HKk/jUYB40cNq4gnxRQaAkISeP2vFcnzhgFhybgdItd+yXrYzqvfQrOiQuA43qvJE/our3nvhVmuAr7NsiXAg6S0rGehvEGqGzTHf65C1SJ+0zuVlBImtYt+ySsfJq19GD3vfoGYGshm4bZl71f9Y+sbtrjuxCbqXgY6Wz1h2gmVEm47fnJIh4F9qfo0oSvzh5EByXT4APMTB/HBRlvwrS+p3LXAbERn2TJYqBe86d0aBgVN0y73eZBB3DfglnDe5me0SQPVqYoAaZ10DaBvteqhwMg6Tf1UloonzaEOKN5g6mxQ256wf1yArI1Gy3uCfY=
    username: AgAZ0kLgm9NNRxtA1w7axBM3SVbPJmcinkiEnqNybZqxQGuz9S4DZ0og9kFBmpC6ElvwLjXp34ifnv0pLc/v4ijLBRhKcusT/bgAZneV2ZP4TcFKACaQ3QXI0Huu+jTM9N8ZZcwu5ZZwfF0mifPj2myJqCzmLBwDLfOkMh/cU/obqhqw7BoW8FEKsSrv9JoulOh2NnMD0bJ4NUumltO1rzeaYDVZzwl2j5KeelB1PorHVWuR8XLIKkn1QEfncodrKrg9FHf7vbL+b3R3qovfgCrPiIMZGLPEIuyG14haHbLVs5DUqbQjPLd9BDVai7plpP0R/td34ixfze8i4fI72mJnmN/Zl4M4Ao/kN0rjjVn312wSAsHCxrkBo0fxKaL6dSSzXioqTllGRCWvEb3Oj0dvRPLkkboibDWVHOVp5F+OAQpIcOcgyYeXsfzKWo2vX4Bje13q4oSXOlMwd02TyRJac0zjQG8PMpE7TJaX8XoD6O5MO14cz3E6uXCBatOd6jXFy3Bwkl8KuMhDglPzO7TSlY7EOJ93uKgE90XEsFrhVsqiLMUtsfCNjY7HpbGW28niEcvrrS9mDpck9EGKEC7+G9tGsMjUMB8x07g5nxUSK4qLIQ+7D6lJEwdRj1HS2QacqmpWj0amYFuSiaE2MX1qAH0uzPDCiWWFoBvOm2s4T6qf8iyQP9FIqAFu8tN9h8qSac4idw8YTYXZPxA=
  template:
    metadata:
      name: postgres-credentials
      namespace: url-shortener-staging
